# ---------------- Server ----------------
server.port=8080

# ---------------- PostgreSQL ----------------
# Pehle PostgreSQL me ek database bana lein:  CREATE DATABASE ecommerce_db;
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=modus@12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------- JPA / Hibernate ----------------
# update = tables khud-ba-khud create/alter ho jayenge entity classes se
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# data.sql tables create hone ke BAAD chale (taaki insert fail na ho)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ---------------- JWT ----------------
# Production me isse environment variable se lena chahiye, hardcode nahi karna chahiye
jwt.secret=ChangeThisToALongRandomSecretKeyForJwtSigningMinimum256Bits
jwt.expiration-ms=86400000

# ---------------- Default Admin (auto-created on first run if not present) ----------------
admin.default.username=Ravisingh
admin.default.password=ravi123
